#!/bin/bash

if [ ! -d "./bin" ]; then
  mkdir bin
fi

rm ./bin/*

#
# Generate Protobuf Code
#
protoc-c --c_out=./xpplugin/ protobuf/ZeroPlane.proto

#
# Compile & Link Plugin
#

# Compiler flags
DEBUG_FLAG='-g'
PROTOBUF_INCL=$(pkg-config --cflags libprotobuf-c)
ZMQ_INCL="-I/usr/local/include"
INCLUDE_FLAGS="-I./SDK/CHeaders/XPLM -I./SDK/CHeaders/Widgets -I./xpplugin/ $PROTOBUF_INCL $ZMQ_INCL"
MACROS_FLAGS="-DAPL=1 -DIBM=0 -DLIN=0 -DXPLM200=1"

CC="clang -c $DEBUG_FLAG $INCLUDE_FLAGS $MACROS_FLAGS"

# Build All C Files
for file in $(find . | grep \\.c$);
do
    fileName=$(basename $file)
    noExt="${fileName%.*}"
    
    `$CC $file -o ./bin/${noExt}.o`
done

# Link
LD="clang -bundle"
ARCH="-arch x86_64 -mmacosx-version-min=10.6"
OTHER_LDFLAGS="-single_module"
PROTOBUF_LINK=$(pkg-config --libs libprotobuf-c)
ZMQ_LINK="-L/usr/local/lib -lzmq"
EXPORT_FLAGS="-Wl,-exported_symbol -Wl,_XPluginStart -Wl,-exported_symbol -Wl,_XPluginEnable -Wl,-exported_symbol -Wl,_XPluginReceiveMessage -Wl,-exported_symbol -Wl,_XPluginDisable -Wl,-exported_symbol -Wl,_XPluginStop"
FRAMEWORK_INCL="-FSDK/Libraries/Mac"
FRAMEWORKS="-framework OpenGL -framework CoreFoundation -framework XPLM -framework XPWidgets"
LIBS="-L./bin/ $PROTOBUF_LINK $ZMQ_LINK"
LINK_FLAGS="$PROTOBUF_LINK"

$LD $ARCH $OTHER_LDFLAGS $LIBS $FRAMEWORK_INCL $FRAMEWORKS $EXPORT_FLAGS ./bin/*.o -o ./bin/pierres_plugin.xpl