/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: protobuf/ZeroPlane.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "protobuf/ZeroPlane.pb-c.h"
void   zero_plane_msg__init
                     (ZeroPlaneMsg         *message)
{
  static ZeroPlaneMsg init_value = ZERO_PLANE_MSG__INIT;
  *message = init_value;
}
size_t zero_plane_msg__get_packed_size
                     (const ZeroPlaneMsg *message)
{
  assert(message->base.descriptor == &zero_plane_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t zero_plane_msg__pack
                     (const ZeroPlaneMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &zero_plane_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t zero_plane_msg__pack_to_buffer
                     (const ZeroPlaneMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &zero_plane_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ZeroPlaneMsg *
       zero_plane_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ZeroPlaneMsg *)
     protobuf_c_message_unpack (&zero_plane_msg__descriptor,
                                allocator, len, data);
}
void   zero_plane_msg__free_unpacked
                     (ZeroPlaneMsg *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &zero_plane_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   attitude__init
                     (Attitude         *message)
{
  static Attitude init_value = ATTITUDE__INIT;
  *message = init_value;
}
size_t attitude__get_packed_size
                     (const Attitude *message)
{
  assert(message->base.descriptor == &attitude__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t attitude__pack
                     (const Attitude *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &attitude__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t attitude__pack_to_buffer
                     (const Attitude *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &attitude__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Attitude *
       attitude__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Attitude *)
     protobuf_c_message_unpack (&attitude__descriptor,
                                allocator, len, data);
}
void   attitude__free_unpacked
                     (Attitude *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &attitude__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   airplane__init
                     (Airplane         *message)
{
  static Airplane init_value = AIRPLANE__INIT;
  *message = init_value;
}
size_t airplane__get_packed_size
                     (const Airplane *message)
{
  assert(message->base.descriptor == &airplane__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t airplane__pack
                     (const Airplane *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &airplane__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t airplane__pack_to_buffer
                     (const Airplane *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &airplane__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Airplane *
       airplane__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Airplane *)
     protobuf_c_message_unpack (&airplane__descriptor,
                                allocator, len, data);
}
void   airplane__free_unpacked
                     (Airplane *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &airplane__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor zero_plane_msg__field_descriptors[2] =
{
  {
    "attitude",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ZeroPlaneMsg, attitude),
    &attitude__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "airplane",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ZeroPlaneMsg, airplane),
    &airplane__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned zero_plane_msg__field_indices_by_name[] = {
  1,   /* field[1] = airplane */
  0,   /* field[0] = attitude */
};
static const ProtobufCIntRange zero_plane_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor zero_plane_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ZeroPlaneMsg",
  "ZeroPlaneMsg",
  "ZeroPlaneMsg",
  "",
  sizeof(ZeroPlaneMsg),
  2,
  zero_plane_msg__field_descriptors,
  zero_plane_msg__field_indices_by_name,
  1,  zero_plane_msg__number_ranges,
  (ProtobufCMessageInit) zero_plane_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor attitude__field_descriptors[6] =
{
  {
    "pitch",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Attitude, pitch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "roll",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Attitude, roll),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "yaw",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Attitude, yaw),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "altitude",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Attitude, altitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vertical_speed",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Attitude, vertical_speed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "heading",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Attitude, heading),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned attitude__field_indices_by_name[] = {
  3,   /* field[3] = altitude */
  5,   /* field[5] = heading */
  0,   /* field[0] = pitch */
  1,   /* field[1] = roll */
  4,   /* field[4] = vertical_speed */
  2,   /* field[2] = yaw */
};
static const ProtobufCIntRange attitude__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor attitude__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Attitude",
  "Attitude",
  "Attitude",
  "",
  sizeof(Attitude),
  6,
  attitude__field_descriptors,
  attitude__field_indices_by_name,
  1,  attitude__number_ranges,
  (ProtobufCMessageInit) attitude__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor airplane__field_descriptors[8] =
{
  {
    "plane_num",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Airplane, plane_num),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tailnum",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Airplane, tailnum),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "has_stallwarn",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Airplane, has_stallwarn),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vso",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Airplane, vso),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vs",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Airplane, vs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vfe",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Airplane, vfe),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vno",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Airplane, vno),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vne",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Airplane, vne),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned airplane__field_indices_by_name[] = {
  2,   /* field[2] = has_stallwarn */
  0,   /* field[0] = plane_num */
  1,   /* field[1] = tailnum */
  5,   /* field[5] = vfe */
  7,   /* field[7] = vne */
  6,   /* field[6] = vno */
  4,   /* field[4] = vs */
  3,   /* field[3] = vso */
};
static const ProtobufCIntRange airplane__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor airplane__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Airplane",
  "Airplane",
  "Airplane",
  "",
  sizeof(Airplane),
  8,
  airplane__field_descriptors,
  airplane__field_indices_by_name,
  1,  airplane__number_ranges,
  (ProtobufCMessageInit) airplane__init,
  NULL,NULL,NULL    /* reserved[123] */
};
