/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: protobuf/ZeroPlane.proto */

#ifndef PROTOBUF_C_protobuf_2fZeroPlane_2eproto__INCLUDED
#define PROTOBUF_C_protobuf_2fZeroPlane_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1000001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Zeroplane__ZeroPlaneMsg Zeroplane__ZeroPlaneMsg;
typedef struct _Zeroplane__Attitude Zeroplane__Attitude;
typedef struct _Zeroplane__Airplane Zeroplane__Airplane;


/* --- enums --- */


/* --- messages --- */

struct  _Zeroplane__ZeroPlaneMsg
{
  ProtobufCMessage base;
  Zeroplane__Attitude *attitude;
  Zeroplane__Airplane *airplane;
};
#define ZEROPLANE__ZERO_PLANE_MSG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&zeroplane__zero_plane_msg__descriptor) \
    , NULL, NULL }


struct  _Zeroplane__Attitude
{
  ProtobufCMessage base;
  float pitch;
  float roll;
  float yaw;
  float altitude;
  float vertical_speed;
  float heading;
};
#define ZEROPLANE__ATTITUDE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&zeroplane__attitude__descriptor) \
    , 0, 0, 0, 0, 0, 0 }


struct  _Zeroplane__Airplane
{
  ProtobufCMessage base;
  int32_t plane_num;
  char *tailnum;
  protobuf_c_boolean has_stallwarn;
  float vso;
  float vs;
  float vfe;
  float vno;
  float vne;
};
#define ZEROPLANE__AIRPLANE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&zeroplane__airplane__descriptor) \
    , 0, NULL, 0, 0, 0, 0, 0, 0 }


/* Zeroplane__ZeroPlaneMsg methods */
void   zeroplane__zero_plane_msg__init
                     (Zeroplane__ZeroPlaneMsg         *message);
size_t zeroplane__zero_plane_msg__get_packed_size
                     (const Zeroplane__ZeroPlaneMsg   *message);
size_t zeroplane__zero_plane_msg__pack
                     (const Zeroplane__ZeroPlaneMsg   *message,
                      uint8_t             *out);
size_t zeroplane__zero_plane_msg__pack_to_buffer
                     (const Zeroplane__ZeroPlaneMsg   *message,
                      ProtobufCBuffer     *buffer);
Zeroplane__ZeroPlaneMsg *
       zeroplane__zero_plane_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   zeroplane__zero_plane_msg__free_unpacked
                     (Zeroplane__ZeroPlaneMsg *message,
                      ProtobufCAllocator *allocator);
/* Zeroplane__Attitude methods */
void   zeroplane__attitude__init
                     (Zeroplane__Attitude         *message);
size_t zeroplane__attitude__get_packed_size
                     (const Zeroplane__Attitude   *message);
size_t zeroplane__attitude__pack
                     (const Zeroplane__Attitude   *message,
                      uint8_t             *out);
size_t zeroplane__attitude__pack_to_buffer
                     (const Zeroplane__Attitude   *message,
                      ProtobufCBuffer     *buffer);
Zeroplane__Attitude *
       zeroplane__attitude__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   zeroplane__attitude__free_unpacked
                     (Zeroplane__Attitude *message,
                      ProtobufCAllocator *allocator);
/* Zeroplane__Airplane methods */
void   zeroplane__airplane__init
                     (Zeroplane__Airplane         *message);
size_t zeroplane__airplane__get_packed_size
                     (const Zeroplane__Airplane   *message);
size_t zeroplane__airplane__pack
                     (const Zeroplane__Airplane   *message,
                      uint8_t             *out);
size_t zeroplane__airplane__pack_to_buffer
                     (const Zeroplane__Airplane   *message,
                      ProtobufCBuffer     *buffer);
Zeroplane__Airplane *
       zeroplane__airplane__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   zeroplane__airplane__free_unpacked
                     (Zeroplane__Airplane *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Zeroplane__ZeroPlaneMsg_Closure)
                 (const Zeroplane__ZeroPlaneMsg *message,
                  void *closure_data);
typedef void (*Zeroplane__Attitude_Closure)
                 (const Zeroplane__Attitude *message,
                  void *closure_data);
typedef void (*Zeroplane__Airplane_Closure)
                 (const Zeroplane__Airplane *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor zeroplane__zero_plane_msg__descriptor;
extern const ProtobufCMessageDescriptor zeroplane__attitude__descriptor;
extern const ProtobufCMessageDescriptor zeroplane__airplane__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_protobuf_2fZeroPlane_2eproto__INCLUDED */
